name: Deploy Angular App to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Remove old files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: "rm -rf /var/www/marcelschliwka.de/*"

      - name: Deploy to Server using Rsync
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }}" dist/marcelschliwka.de/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/marcelschliwka.de

      - name: Clean up build
        run: rm -rf dist/
